### ISSUE TITLE
Pytorch and CUDA version

### ISSUE THREAD

**Issue by WH8Han** [CannyLab/summary_loop#10]
hello, what's the version of your pytorch and cuda? I tried many versions but all failed.

**Comment by tingofurro** [comment]
Hello Han,

The code should work with most versions of Cuda. Most of the code was developed and trained in Cuda 9, but I have also gotten it running on Cuda 10.0 and Cuda 10.2 (tested today).

I think the trickier part is to align Pytorch and Transformers:
In the requirements.txt I recommend transformers==3.1.0.
I don't recommend a particular version of torch, as I think it will automatically pick one that's compatible, but for reference, I am using torch==1.7.0 (with Cuda 10.2) and it is working out of the box.

Choosing the right torch version is a bit tricky and depends on the Cuda you have installed (as well as OS). I usually use this page: https://pytorch.org/get-started/previous-versions/ to decide which Torch version to install, it is kept up to date.

Hope this helps, if you share the error message you're getting I can try to help more!
And sorry for the delay!

Philippe
