### ISSUE TITLE
Missing Model to run example

### ISSUE THREAD

**Issue by raviolli** [CannyLab/summary_loop#4]
I'm trying to run the example:

`python train_summary_loop.py --experiment wikinews_test --dataset_file ../data/wikinews.db --root_folder ../ --device cuda`

but it seems I'm missing the ../models/fluency_news_bs32.bin

it doesn't seem to be in the list of downloadable models. Mistake??

**Comment by tingofurro** [comment]
Hey,
I have re-uploaded it to the Release, it had uploaded partially and failed silently...
Philippe
