### ISSUE TITLE
a sample of data in hdf5 format

### ISSUE THREAD

**Issue by azagsam** [CannyLab/summary_loop#5]
Hi,

I'm trying to train the models from scratch since I'd like to use them on a different language. It seems that one needs a dataset in hdf5 format instead of SQL to do that. Can you please release a sample of data in hdf5 format?

Thanks

**Comment by tingofurro** [comment]
Hello azagsam,

Sorry about that, I've pushed an update, now all scripts should work with the SQLDataset format. I've also added a [Jupyter Notebook](https://github.com/CannyLab/summary_loop/blob/master/Dataset%20SQLite3%20Example.ipynb) that should help if you want to create a dataset in that format.

Another option is to modify the collate_fn of any script to change the data loading process.

Hope that helps,

Philippe
