### ISSUE TITLE
Are there instructions on how to generate summaries from provided models?

### ISSUE THREAD

**Issue by RevanthRameshkumar** [CannyLab/summary_loop#7]
Hello,
Are there any instructions on how to use the provided bins/joblibs to generate summaries from a file or string?

Thanks!

**Comment by tingofurro** [comment]
Hello Revanth,

Sorry for the late reply.
Here's how one could use the pre-trained model to generate a summary:
```
from model_generator import GeneTransformer

generator = GeneTransformer(device="cuda") # Initialize the generator
generator.reload("/path/to/summary_loop_length_61.bin")
document = "This is a long document I want to summarize"

# Have to put in list because the decode function is meant to be used in batches for efficiency.
# You can use a beam size or not (beam_size), and you can use sampling or not (sample), without sampling it does argmax/top_k

summary = generator.decode([document], max_output_length=61, beam_size=1, return_scores=False, sample=False)
```

I hope this helps and sorry for the very late answer...
I love the CRD3 dataset by the way!

Philippe

**Comment by badrinath-reddy** [comment]
Hi,

I could not find "summary_loop_length_61.bin" model in releases, 

Thanks

**Comment by NightMachinery** [comment]
[**@Badrinath Reddy**](https://github.com/badrinath-reddy) commented on [Jun 1, 2021, 11:17 AM GMT+4:30](https://github.com/CannyLab/summary_loop/issues/7#issuecomment-851868621 "2021-06-01T06:47:40Z - Replied by Github Reply Comments"):
> Hi,
> 
> I could not find "summary\_loop\_length\_61.bin" model in releases,
> 
> Thanks

https://github.com/CannyLab/summary_loop/releases/download/v0.1/summary_loop_length46.bin is there though.
