### ISSUE TITLE
Resuming training

### ISSUE THREAD

**Issue by RevanthRameshkumar** [CannyLab/summary_loop#8]
Is resuming training simply starting from the checkpoint instead of the gpt3 copier bin?

For example:

```
#summarizer_model_start = os.path.join(models_folder, "gpt2_copier23.bin")
summarizer_model_start = os.path.join(models_folder, "summarizer_wikinews_test_0_ckpt.bin")
```

**Comment by tingofurro** [comment]
Hello Revanth,

Yes I think you are exactly correct. You can restart the training from any checkpoint in this way.

You can also use the checkpoint as an initial point before finetuning: In one of the experiments for the paper (see Section 5.4), we train the model on the Summary Loop, and then use that checkpoint to finetune the model (supervised) on portions of CNN/DM, and it helps improve performance further.

Hope this helps!

Philippe
